
title: CSpark Research # your title
tagline: Driving Innovation
url: 'https://csparkresearch.in'
baseurl: '' #change it according to your repository name
excerpt_separator: <!--more-->


# Profile information
yourname: CSpark Research
location: New Delhi, India


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url

include: ['expeyes17','projects', 'blocks']

permalink: none
collections:
 expeyes17:
  permalink: /expeyes17/:path.html
  output: true
 projects:
  permalink: /lightblog/:path.html
  output: true
 blocks:
  permalink: /blocks/:path.html
  output: true
 courses:
  permalink: /courses/:path.html
  output: true


# List of links in the navigation bar
navbar-links:
  Products:
    - Alpha Spectrometer: "alphaspec"
    - Gamma Spectrometer: "gammaspec"
    - Gamma-Gamma Coincidence: "gammacoincidence"
    - Multi Channel Analyzer: "mca1k"
    - SEELab 3.0: "seelab3"
    - ExpEYES: "expeyes17"
    - KuttyPy: "kuttypy"
    - KuttyPy Plus: "kuttypyplus"
    - Geiger Counter: "gmcounter"
    - All Products: ""
  Resources:
    - Blog: expeyes17/blog
    - CNSPEC software: "cnspec"
    - In the News: "news"
    - Publications: "publications"
    - CNSPEC software: "cnspec"
    - Outreach Gallery: "imagegallery"
    - Seelab-jr development history: "expeyes-dev"
    - Remote Labs : "remotelabs"
    - SEELablet(EOL): "seelablet/seelablet.html"
    - Downloads: "downloads"
    - GitHub : "https://github.com/csparkresearch"
  Contact Us: "contact"
  About Us: "about"


# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "assets/images/avatar-icon.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
title-img: "/assets/images/logo_transparent.png"

# sidebar post summary defaults
defaults:
  -
    scope:
      path: "_posts"
    values:
      sidebarposts: ["kuttypy","manufacturing","expeyes17","seelablet"]



markdown: kramdown
highlighter: rouge

kramdown:
 highlighter: rouge
 input: GFM

plugins:
  - jekyll-sitemap
