AlphaSpec-1K:
  name: Alpha Spectrometer
  link: "alphaspec"
  description: "A compact Alpha Spectrometer with integrated 1K MCA"
  user-manual: "/assets/pdfs/alphaspec manual.pdf"
  windows: "https://drive.google.com/file/d/1I3P4WKphknajXaO2GgtFZJ0DyyfqLaiR/view"
  ubuntu: "/assets/installers/cnspec-5.0.7.deb"
  installdescription: "Tested on Ubuntu 18.04 and Windows 7/10"
  papers:
    Expts with 212-Bi: "/assets/pdfs/alpha1.pdf"
    Instrument model: "/assets/pdfs/alpha2.pdf"
  image: Alpha_thumb.jpg

MCA-1K:
  name: Multi Channel Analyzer
  link: "mca1k"
  description: "Multi-channel Analyzer"
  image: mca_gallery_thumb.jpg
  user-manual: "/assets/pdfs/alphaspec manual.pdf"
  windows: "https://drive.google.com/file/d/1I3P4WKphknajXaO2GgtFZJ0DyyfqLaiR/view"
  ubuntu: "/assets/installers/cnspec-5.0.7.deb"

GammaSpec-1K:
  name: Gamma Spectrometer
  description: "Gamma Spectrometer"
  link: "gammaspec"
  image: gamma_pic.png
  user-manual: "/assets/pdfs/gammaspec manual.pdf"
  installdescription: "Tested on Ubuntu 18.04 and Windows 7/10"
  windows: "https://drive.google.com/uc?export=download&id=16hRQM7tZ8W7t4KYA9uht2PFLlR_6SZi5"
  ubuntu: "/assets/installers/cnspec-5.0.7.deb"
  papers:
    DAE-SYMPNP: "http://sympnp.org/proceedings/63/G19.pdf"
    RINP2: "https://indico.cern.ch/event/763807/contributions/3274494/contribution.pdf"

GammaCoincidence:
  name: Gamma-Gamma Coincidence
  description: "Gamma-Gamma Coincidence setup"
  link: "gammacoincidence"
  image: gamma_pic.png
  user-manual: "/assets/pdfs/gammaspec manual.pdf"
  windows: "https://drive.google.com/uc?export=download&id=1uokmxXdJCwO407mIib4HG4VZj-PoTL8W"
  ubuntu: "/assets/installers/cnspec-5.0.7.deb"
  papers:
    DAE-SYMPNP: "http://sympnp.org/proceedings/63/G19.pdf"
    RINP2: "https://indico.cern.ch/event/763807/contributions/3274494/contribution.pdf"


SEELab3:
  name: SEELab-3.0
  link: "seelab3"
  description: "Your Lab @ Home ..."
  installdescription: "The software for SEELab3 is shared with its predecessor ExpEYES17. The interface dynamically adapts to the connected device."
  user-manual: "/assets/pdfs/SEELab3.pdf"
  windows: "https://drive.google.com/file/d/1zqFQzjDyJEFbQ0OfOQ2DNQUUXBl8iELh/view?usp=sharing"
  ubuntu: "/assets/installers/eyes17_5.0+pyqt5-7_all.deb"
  android: "https://play.google.com/store/apps/details?id=com.cspark.research.eyes17"
  source: "/assets/installers/eyes17-4.9.0.zip"
  apidocs: "https://eyes17lib.readthedocs.io/en/latest/"
  image: expeyes_thumb.jpg

ExpEYES17:
  name: ExpEYES-17
  link: "expeyes17"
  description: "Your Lab @ Home ..."
  installdescription: "Tested on Ubuntu 18.04,Windows 7/10, Android 9+"
  user-manual: "/assets/pdfs/expeyes17.pdf"
  windows: "https://drive.google.com/file/d/1zqFQzjDyJEFbQ0OfOQ2DNQUUXBl8iELh/view?usp=sharing"
  ubuntu: "/assets/installers/eyes17_5.0+pyqt5-7_all.deb"
  android: "https://play.google.com/store/apps/details?id=com.cspark.research.eyes17"
  source: "/assets/installers/eyes17-4.9.0.zip"
  apidocs: "https://eyes17lib.readthedocs.io/en/latest/"
  image: expeyes_thumb.jpg



KuttyPy:
  name: KuttyPy
  link: "kuttypy"
  description: "Interactive Playground [Microcontroller Training Utility]"
  image: kpy_thumb.gif
  user-manual: "https://kuttypy.readthedocs.io/en/latest/"
  installdescription: "Tested on Ubuntu 18.04 and Windows 7/10"
  android: "https://play.google.com/store/apps/details?id=com.cspark.kuttypy"
  ubuntu: "/assets/installers/KuttyPy-1.0.19.deb"
  apidocs: "https://kuttypy.readthedocs.io/en/latest/"
  windows: "https://drive.google.com/uc?export=download&id=18PD-Llx12PTfMRWlHA447TCMxTA6smWZ"

KuttyPyPlus:
  name: KuttyPyPlus
  link: "kuttypyplus"
  description: "Interactive Playground [Microcontroller Training Utility]"
  image: kpy_thumb.gif
  installdescription: "Tested on Ubuntu 18.04 and Windows 7/10"
  user-manual: "https://kuttypy.readthedocs.io/en/latest/"
  android: "https://play.google.com/store/apps/details?id=com.cspark.kuttypy"
  ubuntu: "/assets/installers/KuttyPy-1.0.19.deb"
  windows: "https://drive.google.com/uc?export=download&id=18PD-Llx12PTfMRWlHA447TCMxTA6smWZ"
  apidocs: "https://kuttypy.readthedocs.io/en/latest/"


GMCounter:
  name: GMCounter
  link: "gmcounter"
  description: "Geiger Counter with USB interface"
  installdescription: "Tested on Ubuntu 18.04 and Windows 7/10"
  image: kpy_thumb.gif
  user-manual: "/assets/pdfs/gm manual.pdf"
  ubuntu: "/assets/installers/gmc-1.0.0.deb"
  windows: "#"


